config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :venues
  get 'pages/index'

  get 'pages/contact'

  get 'pages/about'

  root 'venues#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  first_name             :string
#  last_name              :string
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/venue.rb
# == Schema Information
#
# Table name: venues
#
#  id          :integer          not null, primary key
#  name        :string
#  address     :string
#  city        :string
#  state       :string
#  zip         :string
#  phone       :string
#  fax         :string
#  email       :string
#  description :string
#  lat         :decimal(, )
#  long        :decimal(, )
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Venue < ActiveRecord::Base
  attachment :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def contact
  end

  def about
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :authenticate_user!
  def index
    @venues = Venue.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AbehsaWeddings</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">AbeshaWire</a>
          </div>
          <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to 'About', pages_about_url %></li>
              <li><%= link_to 'Venues', venues_url %></li>
              <li><%= link_to 'Contact Us', pages_contact_url %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li><%= link_to current_user.first_name, edit_user_registration_url %></li>
                <li><%= link_to 'Log Out', destroy_user_session_url, method: :delete %></li>
              <% else %>
                <li><%= link_to 'Sign In', new_user_session_url %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </nav>

      <div class="container">
        <% if flash[:notice] %>
          <p class="notice alert alert-success" role="alert"><%= notice %></p>
        <% end %>
        <% if flash[:alert] %>
          <p class="alert alert alert-danger" role="alert"><%= alert %></p>
        <% end %>
        <%= yield %>

      </div>


</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/venues/index.html.erb
<h1>Venues</h1>
<p>
  This are the venues
</p>
<div class="row">
  <% @venues.each do |venue| %>
    <div class="col-lg-3 col-sm-6 col-md-4">
      <div class="venue">
        <h1><%= venue.name %></h1>
        <p><%= venue.address %></p>
        <p><%= venue.city %>, <%= venue.state %>
        <%= venue.zip %><p>
        <p><%= venue.description %></p>
      </div>
    </div>
  <% end %>
</div>